### PR TITLE
Replace CRLF line endings with LF

### PR DESCRIPTION
**Pull request by haydn**
I've notices a number of people who've forked Flixel have done this change independently, but if we can fix it at the source it'll make merging changes back easier.

### CODE REVIEW

**Comment by AdamAtomic** [comment]
i have no idea if this is Windows/Linux-safe or how to make sure that I maintain LF-only endings when I edit locally in Flash Builder...

**Comment by haydn** [comment]
Hey Adam,

I've no idea where these CRLF line endings would be coming from as there's only a handful of files that are affected. I'm not very familiar with Flash Builder, but I'd be surprised if it was adding them. Perhaps it just uses the most common line ending in the files it opens? Most of the files in the repo are already using LF endings.

I assume this pull request won't merge cleanly now because of all the recent changes, but if you'd like I can open a new pull request based off the dev branch with the line endings normalised to LF again. Making them consistent within the repo (as either CRLF or LF) will make merges easier to deal with in the future.

Cheers,

Haydn

**Comment by AdamAtomic** [comment]
cool - yea if MOST of the files are on just LF already, and you have a way to easily mend the outliers, that would be awesome!  you would have the honor of being the first accepted pull request :D

**Comment by goshki** [comment]
Doesn't the Git itself maintain the proper (i.e. preferred by you) line-endings no matter what they are in the remote repository?

**Comment by haydn** [comment]
I've opened a new pull request: https://github.com/AdamAtomic/flixel/pull/132

@goshki I believe it does do something behind the scenes to help, but I've never been able to get everything working perfectly when there's different line endings being used at each end. In my experience the safest and simplest option is for everyone to work with the same line endings, which isn't really a hassle these days as all good text editors handle LF.

**Pull request closed without merging**
