### PR TITLE
Invalid debug frame for sprite with non zero offset

### PR DESCRIPTION
**Pull request by Werdn**
Fixed

### CODE REVIEW

**Comment by Werdn** [comment]
FlxCamera.update() has this bug too

**Comment by AdamAtomic** [comment]
is this still a problem on the latest dev branch?  can you explain what's happening with it?  thanks!

**Comment by Werdn** [comment]
FlxObject has no «offset» value, and we get invalid bounding box for drawings and camera box moving.
Tomorrow I will look at the latest branch.

**Comment by AdamAtomic** [comment]
bounding boxes for sprites are valid and rendered the way they're supposed to right now. bounding boxes represent collisions only and have nothing to do with offsets or graphics rendering.  I'm not sure what you mean by "invalid"

**Comment by Werdn** [comment]
latest dev branch:
http://img850.imageshack.us/i/flixelbug.png/ — bug in camera box (not fixed by me)
http://img191.imageshack.us/i/flixelbug2.png/

**Comment by AdamAtomic** [comment]
i'm guessing you're using a physics engine?  including the offset fix you suggested would break debug bounding box display for most objects.  I would recommend jsut writing your own debugDraw routine for the physics objects that takes the offset and angle into account

**Comment by AdamAtomic** [comment]
for example if you have your own class WerdnSprite that is a physical object, etc, then you should be able to just override debugDraw() in that class and give it your own behavior, so that the visual debugger is still useful for your project :)

**Comment by Werdn** [comment]
Another static sprites with offset have invalid frame position, they are instances of FlxSprite, look at stairs on screen-shot. Physics objects are invisible at all.
Camera has bad behavior with invalid bounding box of player's object (first screen) — this is definitely a bug. On left side spacing will be player's position, at right side — player's position + player's width + player's offset.

But yes, my fix is wrong, I'll try to improve it.

**Pull request closed without merging**
